language: php

cache:
    directories:
        - $HOME/.cache/composer

#install:
#  - scripts/install.sh

script:
    - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --optimize-autoloader
    - ./scripts/phpunit.sh
