language: php

cache:
    directories:
        - $HOME/.cache/composer

addons:
    mariadb: '10.1'

env:
    global:
        - PIMCORE_ENVIRONMENT=test
        - PIMCORE_TEST=1
        - PIMCORE_TEST_DB_DSN="mysql://root@localhost/pimcore_test"


install:
    - ./scripts/install.sh

script:
    - ./scripts/phpunit.sh
